export type OriginRecord = {
  record_id: number,
  youtube_record_id: number,
  season_key: string,
  playlist_id: string,
  playlist_title: string,
  video_id: string,
  video_title: string,
  video_description: string,
  anime_title: string,
  song_title: string,
  song_order: number,
  op_or_ed: "OP" | "ED",
  vocal: string,
  guiter: string,
  key: string,
  violin: string,
  bass: string,
  drum: string,
  mix: string,
  mastering: string,
  movie: string,
};

export type SongRecord = {
  season_key: string,
  playlist_title: string,
  video_id: string,
  video_title: string,
  anime_title: string,
  song_title: string,
  song_order: number,
  op_or_ed: "OP" | "ED",
  vocal: string | null,
  guiter: string | null,
  key: string | null,
  violin: string | null,
  bass: string | null,
  drum: string | null,
  mix: string | null,
  mastering: string | null,
  movie: string | null,
};

export type Playlist = {
  id: string,
  name: string,
  is_predefined: boolean,
  records: SongRecord[],
};
